//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserName { get; set; }
        public string ItemName { get; set; }
        public string ShopName { get; set; }
        public double Price { get; set; }
    }
}
