//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItem
    {
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string ItemName { get; set; }
        public string Type { get; set; }
        public float Price { get; set; }
        public System.DateTime PurchaseTime { get; set; }
    }
}
