#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PriceCompEngnMobile.Resource", IsApplication=true)]

namespace PriceCompEngnMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_google_signin_btn_text_dark = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_light = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddBtn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Cart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int check = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cmpr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int filter_btn = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Group = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int List = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Location = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Login = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Logo = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Options = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int reg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int scan = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int shop = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Shopping = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int stats = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int trend = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int trend2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int upload = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Validate = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070036
			public const int addBtn = 2131165238;
			
			// aapt resource value: 0x7f07000e
			public const int add_item = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int adjust_height = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int adjust_width = 2131165190;
			
			// aapt resource value: 0x7f070025
			public const int around_me = 2131165221;
			
			// aapt resource value: 0x7f07000a
			public const int auto = 2131165194;
			
			// aapt resource value: 0x7f070031
			public const int cartBtn = 2131165233;
			
			// aapt resource value: 0x7f070013
			public const int checkbox_iki = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int checkbox_lidl = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int checkbox_maxima = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int checkbox_norfa = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int checkbox_rimi = 2131165199;
			
			// aapt resource value: 0x7f070017
			public const int compare_button = 2131165207;
			
			// aapt resource value: 0x7f07000b
			public const int dark = 2131165195;
			
			// aapt resource value: 0x7f070028
			public const int emailTxt = 2131165224;
			
			// aapt resource value: 0x7f070000
			public const int hybrid = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int icon_only = 2131165191;
			
			// aapt resource value: 0x7f070021
			public const int image = 2131165217;
			
			// aapt resource value: 0x7f070035
			public const int imgView = 2131165237;
			
			// aapt resource value: 0x7f070033
			public const int item_name = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int item_purchase_times = 2131165236;
			
			// aapt resource value: 0x7f07000c
			public const int light = 2131165196;
			
			// aapt resource value: 0x7f070030
			public const int list_cheapest = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int list_pop_alltime = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int list_pop_week = 2131165230;
			
			// aapt resource value: 0x7f070032
			public const int locationBtn = 2131165234;
			
			// aapt resource value: 0x7f07001e
			public const int login = 2131165214;
			
			// aapt resource value: 0x7f070022
			public const int map = 2131165218;
			
			// aapt resource value: 0x7f070001
			public const int none = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int normal = 2131165186;
			
			// aapt resource value: 0x7f07001c
			public const int passwordTxt = 2131165212;
			
			// aapt resource value: 0x7f070026
			public const int pw1Txt = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int pw2Txt = 2131165223;
			
			// aapt resource value: 0x7f070023
			public const int radiusText = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int regBtn = 2131165225;
			
			// aapt resource value: 0x7f07001d
			public const int register = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int result_text_row1 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int result_text_row2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int result_text_row3 = 2131165206;
			
			// aapt resource value: 0x7f070003
			public const int satellite = 2131165187;
			
			// aapt resource value: 0x7f07001f
			public const int scan = 2131165215;
			
			// aapt resource value: 0x7f070019
			public const int search_button = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int search_items_list = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int search_items_text = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int shop = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int shopText = 2131165220;
			
			// aapt resource value: 0x7f07000d
			public const int shop_cart_fragment_container = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int standard = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int terrain = 2131165188;
			
			// aapt resource value: 0x7f07002d
			public const int textView2 = 2131165229;
			
			// aapt resource value: 0x7f070039
			public const int textVw = 2131165241;
			
			// aapt resource value: 0x7f07002a
			public const int text_name = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int text_price = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int text_type = 2131165228;
			
			// aapt resource value: 0x7f070038
			public const int uploadBtn = 2131165240;
			
			// aapt resource value: 0x7f07001b
			public const int usernameTxt = 2131165211;
			
			// aapt resource value: 0x7f070037
			public const int validBtn = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int validateBtn = 2131165242;
			
			// aapt resource value: 0x7f070009
			public const int wide = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_shopcart = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int add_item_prompt = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_shop_cart_list = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int register = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int shop_cart_list_row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Shoping = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int top_5_list_row = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Upload = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int validate = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int app_name = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int google_maps_key = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
